/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'fsamin' at '29/01/15 20:11' with Gradle 2.1
 *
 * @author fsamin, @date 29/01/15 20:11
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
