/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'fsamin' at '29/01/15 20:11' with Gradle 2.1
 *
 * @author fsamin, @date 29/01/15 20:11
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
